### ISSUE TITLE
NameError: uninitialized constant Alexa::Connection::URI

### ISSUE THREAD

**Issue by mm580486** [morgoth/alexa#12]
i have some problem on alexa gem

i setting my credentials and start to send request but alexa gem return this error 
```

 url_info = client.url_info(url: "http://google.com")
NameError: uninitialized constant Alexa::Connection::URI
	from /Users/mac/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/alexa-0.6.3/lib/alexa/connection.rb:59:in `uri'
	from /Users/mac/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/alexa-0.6.3/lib/alexa/connection.rb:47:in `request'
	from /Users/mac/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/alexa-0.6.3/lib/alexa/connection.rb:26:in `get'
	from /Users/mac/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/alexa-0.6.3/lib/alexa/api/url_info.rb:14:in `fetch'
	from /Users/mac/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/alexa-0.6.3/lib/alexa/client.rb:27:in `url_info'
```

**Comment by pboling** [comment]
The gem doesn't delcare it's dependencies properly.  This is a bug in the gem, but there is a workaround, `require 'uri'` at the top of your file, or in an initializer / boot strapper.
